### ISSUE TITLE
Keep getting this error

### ISSUE THREAD

**Issue by creiti** [ucarno/ow-league-tokens#15]
[2022-10-25 20:54:24,807 - ERROR] Task exception was never retrieved
future: <Task finished name='Task-2717' coro=<Farmer.update_data() done, defined at farmer.py:112> exception=ClientConnectorError(ConnectionKey(host='overwatchleague.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=8072226711955236250), gaierror(11004, 'getaddrinfo failed'))>
Traceback (most recent call last):
  File "aiohttp\connector.py", line 1152, in _create_direct_connection
  File "aiohttp\connector.py", line 874, in _resolve_host
  File "aiohttp\resolver.py", line 33, in resolve
  File "asyncio\base_events.py", line 860, in getaddrinfo
  File "concurrent\futures\thread.py", line 58, in run
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "farmer.py", line 115, in update_data
  File "farmer.py", line 103, in get_next_data
  File "aiohttp\client.py", line 1141, in __aenter__
  File "aiohttp\client.py", line 536, in _request
  File "aiohttp\connector.py", line 540, in connect
  File "aiohttp\connector.py", line 901, in _create_connection
  File "aiohttp\connector.py", line 1166, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host overwatchleague.com:443 ssl:default [getaddrinfo failed]

**Comment by ucarno** [comment]
Are you running this script from your computer? Is https://overwatchleague.com/ website accessible from your browser?

**Comment by creiti** [comment]
The script is running from my computer and am able to access the website from my browser

**Comment by ucarno** [comment]
Seems like something is wrong with your DNS settings, can't really help here
