### ISSUE TITLE
Compatability with the new player profile system

### ISSUE THREAD

**Issue by catalpaaa** [ucarno/ow-league-tokens#33]
After the new ow2 profile system comes online, adding account by btag outputs an error,

> Adding an account...
What is your username? (for example myUsername or myUsername#1234) - leave blank to exit
­­­­­­ ­ ­ ­ ­ example#123456
Traceback (most recent call last):
  File "path/ow-league-tokens/src/main.py", line 455, in <module>
    parsed_args.func(parsed_args)
  File "path/ow-league-tokens/src/main.py", line 219, in menu
    account_id = str(user_dict['id'])
KeyError: 'id'

**Comment by catalpaaa** [comment]
nvm the system doesn't return uid anymore
