### ISSUE TITLE
Permission error when using multiple accounts

### ISSUE THREAD

**Issue by tired9494** [ucarno/ow-league-tokens#50]
I have 2 accounts added as separate profiles. One of the accounts starts fine, then the other gives this error. Only one chrome window for the working account is opened. Windows 10. 

```
Exception in thread Thread-6 (start_chrome):
Traceback (most recent call last):
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tired\Downloads\ow-league-tokens-main\src\app.py", line 33, in start_chrome
    driver = uc.Chrome(
             ^^^^^^^^^^
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 246, in __init__
    self.patcher.auto()
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    self.unzip_package(self.fetch_package())
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 180, in unzip_package
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\tired\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver.exe' -> 'C:\\Users\\tired\\appdata\\roaming\\undetected_chromedriver\\undetected_chromedriver.exe'
Exception in thread Thread-5 (start_chrome):
Traceback (most recent call last):
Exception in thread Thread-2 (start_chrome):
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\tired\Downloads\ow-league-tokens-main\src\app.py", line 33, in start_chrome
    self._target(*self._args, **self._kwargs)
    driver = uc.Chrome(
  File "C:\Users\tired\Downloads\ow-league-tokens-main\src\app.py", line 33, in start_chrome
             ^^^^^^^^^^
    driver = uc.Chrome(
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 246, in __init__
             ^^^^^^^^^^
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 246, in __init__
    self.patcher.auto()
    self.patcher.auto()
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 127, in auto
    self.unzip_package(self.fetch_package())
    self.unzip_package(self.fetch_package())
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 180, in unzip_package
  File "C:\Users\tired\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\patcher.py", line 180, in unzip_package
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
    os.rename(os.path.join(self.zip_path, self.exe_name), self.executable_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\tired\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver.exe' -> 'C:\\Users\\tired\\appdata\\roaming\\undetected_chromedriver\\undetected_chromedriver.exe'
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\tired\\appdata\\roaming\\undetected_chromedriver\\undetected\\chromedriver.exe' -> 'C:\\Users\\tired\\appdata\\roaming\\undetected_chromedriver\\undetected_chromedriver.exe'
[2023-04-29 09:36:56,048 - INFO] patching driver executable C:\Users\tired\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
```

**Comment by ucarno** [comment]
Should be fixed in latest commit
