### ISSUE TITLE
[11532] Failed to execute script 'main' due to unhandled exception! Bye!

### ISSUE THREAD

**Issue by LowHighh** [ucarno/ow-league-tokens#55]

**Comment by ucarno** [comment]
Could you please provide full stacktrace?

**Comment by LowHighh** [comment]
[2023-05-01 23:52:05,351 - INFO] patching driver executable C:\Users\Administrator\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "menu.py", line 125, in menu
  File "menu.py", line 85, in <lambda>
  File "app.py", line 203, in bootstrap
  File "app.py", line 76, in start_chrome
  File "app.py", line 76, in <listcomp>
  File "app.py", line 37, in get_driver
  File "undetected_chromedriver\__init__.py", line 441, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 84, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 104, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 286, in __init__
  File "undetected_chromedriver\__init__.py", line 704, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 378, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:56527
from session not created: This version of ChromeDriver only supports Chrome version 112
Current browser version is 107.0.5304.121
Stacktrace:
Backtrace:
        GetHandleVerifier [0x002FDCE3+50899]
        (No symbol) [0x0028E111]
        (No symbol) [0x00195588]
        (No symbol) [0x001B570C]
        (No symbol) [0x001AF5B1]
        (No symbol) [0x001AF391]
        (No symbol) [0x001E1FFE]
        (No symbol) [0x001E1CEC]
        (No symbol) [0x001DB6F6]
        (No symbol) [0x001B7708]
        (No symbol) [0x001B886D]
        GetHandleVerifier [0x00563EAE+2566302]
        GetHandleVerifier [0x005992B1+2784417]
        GetHandleVerifier [0x0059327C+2759788]
        GetHandleVerifier [0x00395740+672048]
        (No symbol) [0x00298872]
        (No symbol) [0x002941C8]
        (No symbol) [0x002942AB]
        (No symbol) [0x002871B7]
        BaseThreadInitThunk [0x76C50099+25]
        RtlGetAppContainerNamedObjectPath [0x77757B6E+286]
        RtlGetAppContainerNamedObjectPath [0x77757B3E+238]
        (No symbol) [0x00000000]

[6976] Failed to execute script 'main' due to unhandled exception!
Bye!

**Comment by LowHighh** [comment]
Solved by re-installing google chrome

**Comment by ucarno** [comment]
Nice! I should add minimal Chrome version to Readme
