### ISSUE TITLE
Idk what happened but it crashed

### ISSUE THREAD

**Issue by TomerGamerTV** [ucarno/ow-league-tokens#77]
This is the first time its happened to me your program never crashed until this moment

```
Message: unknown error: cannot connect to chrome at 127.0.0.1:47827
from chrome not reachable
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00F88893+48451]
	(No symbol) [0x00F1B8A1]
	(No symbol) [0x00E24F20]
	(No symbol) [0x00E1B0E5]
	(No symbol) [0x00E45858]
	(No symbol) [0x00E40151]
	(No symbol) [0x00E3FF31]
	(No symbol) [0x00E70798]
	(No symbol) [0x00E7047C]
	(No symbol) [0x00E6A0B6]
	(No symbol) [0x00E47E08]
	(No symbol) [0x00E48F2D]
	GetHandleVerifier [0x011E8E3A+2540266]
	GetHandleVerifier [0x01228959+2801161]
	GetHandleVerifier [0x0122295C+2776588]
	GetHandleVerifier [0x01012280+612144]
	(No symbol) [0x00F24F6C]
	(No symbol) [0x00F211D8]
	(No symbol) [0x00F212BB]
	(No symbol) [0x00F14857]
	BaseThreadInitThunk [0x75A77D59+25]
	RtlInitializeExceptionChain [0x76EEB74B+107]
	RtlClearBits [0x76EEB6CF+191]


Traceback (most recent call last):
  File "app.py", line 343, in bootstrap
  File "app.py", line 171, in start_chrome
  File "app.py", line 124, in get_driver
  File "app.py", line 59, in get_driver
  File "undetected_chromedriver\__init__.py", line 441, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 84, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 104, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 286, in __init__
  File "undetected_chromedriver\__init__.py", line 704, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 378, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:47827
from chrome not reachable
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00F88893+48451]
	(No symbol) [0x00F1B8A1]
	(No symbol) [0x00E24F20]
	(No symbol) [0x00E1B0E5]
	(No symbol) [0x00E45858]
	(No symbol) [0x00E40151]
	(No symbol) [0x00E3FF31]
	(No symbol) [0x00E70798]
	(No symbol) [0x00E7047C]
	(No symbol) [0x00E6A0B6]
	(No symbol) [0x00E47E08]
	(No symbol) [0x00E48F2D]
	GetHandleVerifier [0x011E8E3A+2540266]
	GetHandleVerifier [0x01228959+2801161]
	GetHandleVerifier [0x0122295C+2776588]
	GetHandleVerifier [0x01012280+612144]
	(No symbol) [0x00F24F6C]
	(No symbol) [0x00F211D8]
	(No symbol) [0x00F212BB]
	(No symbol) [0x00F14857]
	BaseThreadInitThunk [0x75A77D59+25]
	RtlInitializeExceptionChain [0x76EEB74B+107]
	RtlClearBits [0x76EEB6CF+191]

```

**Comment by TomerGamerTV** [comment]
After enabling and disabling headless mode it seems like it's working again idk what haplened. Its possible that it's started working because I launched Google Chrome and closed it?
