### ISSUE TITLE
Program cant connect to chrome

### ISSUE THREAD

**Issue by TomerGamerTV** [ucarno/ow-league-tokens#83]
Chrome is up to date and i disabled the headless option and it still doesn't work

```
Message: unknown error: cannot connect to chrome at 127.0.0.1:59070
from chrome not reachable
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0117A813+48355]
        (No symbol) [0x0110C4B1]
        (No symbol) [0x01015220]
        (No symbol) [0x0100B355]
        (No symbol) [0x01035C68]
        (No symbol) [0x010306B4]
        (No symbol) [0x01030491]
        (No symbol) [0x01060C55]
        (No symbol) [0x0106093C]
        (No symbol) [0x0105A536]
        (No symbol) [0x010382DC]
        (No symbol) [0x010393DD]
        GetHandleVerifier [0x013DAABD+2539405]
        GetHandleVerifier [0x0141A78F+2800735]
        GetHandleVerifier [0x0141456C+2775612]
        GetHandleVerifier [0x012051E0+616112]
        (No symbol) [0x01115F8C]
        (No symbol) [0x01112328]
        (No symbol) [0x0111240B]
        (No symbol) [0x01104FF7]
        BaseThreadInitThunk [0x776100C9+25]
        RtlGetAppContainerNamedObjectPath [0x77977B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77977B1E+238]


Traceback (most recent call last):
  File "app.py", line 343, in bootstrap
  File "app.py", line 171, in start_chrome
  File "app.py", line 124, in get_driver
  File "app.py", line 59, in get_driver
  File "undetected_chromedriver\__init__.py", line 441, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 84, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 104, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 286, in __init__
  File "undetected_chromedriver\__init__.py", line 704, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 378, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 440, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 245, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:59070
from chrome not reachable
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0117A813+48355]
        (No symbol) [0x0110C4B1]
        (No symbol) [0x01015220]
        (No symbol) [0x0100B355]
        (No symbol) [0x01035C68]
        (No symbol) [0x010306B4]
        (No symbol) [0x01030491]
        (No symbol) [0x01060C55]
        (No symbol) [0x0106093C]
        (No symbol) [0x0105A536]
        (No symbol) [0x010382DC]
        (No symbol) [0x010393DD]
        GetHandleVerifier [0x013DAABD+2539405]
        GetHandleVerifier [0x0141A78F+2800735]
        GetHandleVerifier [0x0141456C+2775612]
        GetHandleVerifier [0x012051E0+616112]
        (No symbol) [0x01115F8C]
        (No symbol) [0x01112328]
        (No symbol) [0x0111240B]
        (No symbol) [0x01104FF7]
        BaseThreadInitThunk [0x776100C9+25]
        RtlGetAppContainerNamedObjectPath [0x77977B4E+286]
        RtlGetAppContainerNamedObjectPath [0x77977B1E+238]


[2023-06-29 14:42:01,882 - ERROR] (Oops)
```

**Comment by ucarno** [comment]
Follow these steps and check if app works after each. These actions will fix 99% of problems.

1. Update your browser by going to `chrome://help`
2. Delete `profiles/` folder and sign in to your account(s) again
3. Restart your PC

**Comment by TomerGamerTV** [comment]
> Follow these steps and check if app works after each. These actions will fix 99% of problems.
> 
> 
> 
> 1. Update your browser by going to `chrome://help`
> 
> 2. Delete `profiles/` folder and sign in to your account(s) again
> 
> 3. Restart your PC

The dev updated the app and it seems like it's fixed now
