### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by pavrostiva** [ucarno/ow-league-tokens#92]
I encountered the "UnboundLocalError: cannot access local variable 'browser' where it is not associated with a value" error. I attempted to resolve it using the solution provided in issue #78 . However, now I am encountering a new error when launching the bot:

```
[WinError 2] The system cannot find the file specified

Traceback (most recent call last):
  File "app.py", line 359, in bootstrap
  File "app.py", line 169, in start_chrome
  File "app.py", line 59, in get_driver
  File "undetected_chromedriver\__init__.py", line 421, in __init__
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

The portable Chrome version is 114.0.5735.199, and this is my config.json file:

![image](https://github.com/ucarno/ow-league-tokens/assets/47397695/1715f9ba-5093-4fce-9e41-051fdf555886)

**Comment by omarsaad98** [comment]
For some reason, the app isn't able to handle paths with spaces in them. Try moving the chrome app to a location without spaces in it.

**Comment by pavrostiva** [comment]
> For some reason, the app isn't able to handle paths with spaces in them. Try moving the chrome app to a location without spaces in it.

Thank you for your response. After installing the portable Chrome (version 114.0.5735.199) in a location without spaces in the path, bot is crashing on launch with the following error code:

```
Traceback (most recent call last):
File "main.py", line 72, in <module>
Fila "menu.py", line 100, in menu
File "utils.py", line 55, in load_config
File "json__init__.py", line 346, in loads
File "jsonldecoder.py", line 337, in decode
File "jsonidecoder.py", line 353, in raw_decode json.decoder.JSONDecodeError: Invalid \escape: line 12 column 27 (char 235)
[14056] Failed to execute script 'main' due to unhandled exception!
```

**Comment by omarsaad98** [comment]
Fix yo json, bud. According to the docs, you're supposed to use forward slashes in the path

**Comment by pavrostiva** [comment]
> Fix yo json, bud. According to the docs, you're supposed to use forward slashes in the path


Thanks, man! I appreciate the reminder. I forgot about that, but now the bot is finally working as expected
